package org.ditosoft.kafka;


import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import java.util.Date;

public class Authorization {


    //public int autorizationNumber;
    //public String idOffice;

    @Size(max=8)
    private long AUTORIZACIONES_NUMERO;
    @Size(max=5)
    private String ID_OFICINA;
    private int CODTIPOS_SERVICIO;
    private String NUMIDE;
    private String TIPIDE;
    private String NROCON;
    private int NUMBEN;
    private String AUTORIZACIONES_TIPMEDAUT;
    private long AUTORIZACIONES_NITMEDAUT;
    private String CIUCOD;
    private String IDDIAGNOSTICOS;
    private String IDORIGEN;
    private String AUTORIZACIONES_TIPINS;
    private long AUTORIZACIONES_NUMIDEINS;
    private long AUTORIZACIONES_TIPCON;
    private String AUTORIZACIONES_CORR_DIR;
    private String AUTORIZACIONES_FECHA_EXPED;
    private String AUTORIZACIONES_OBSER;
    private long AUTORIZACIONES_CAURECHA;
    private String AUTORIZACIONES_FECHA_ESTADO;
    private long AUTORIZACIONES_ESTADO;
    private String AUTORIZACIONES_PROINS;
    private String AUTORIZACIONES_PLANORD;
    private long AUTORIZACIONES_VALOR;
    private long AUTORIZACIONES_VALOR_TOTAL;
    private String AUTORIZACIONES_RESPO;
    private String AUTORIZACIONES_FECHA_RADICA;
    private long AUTORIZACIONES_CODOBSERV;
    private long AUTORIZACIONES_COPAGO;
    private long AUTORIZACIONES_MODERA;
    private long AUTORIZACIONES_SEMANAS;
    private String AUTORIZACIONES_ESTRATO;
    private String AUTORIZACIONES_FECHA_ANULA;
    private String AUTORIZACIONES_ANULACION;
    private String AUTORIZACIONES_IPSPRESTA;
    private String AUTORIZACIONES_IPSEXPIDE;
    private String AUTORIZACIONES_HORARAD;
    private String AUTORIZACIONES_ESTANCIA;
    private long AUTORIZACIONES_TIPOATEN;
    private long AUTORIZACIONES_CLASEATEN;
    private long AUTORIZACIONES_CAUANULA;
    private String AUTORIZACIONES_COMPLEMENTO;
    private long AUTORIZACIONES_ACORCAR;
    private String AUTORIZACIONES_IMPRESA;
    private long AUTORIZACIONES_PRO_ACOR_A;
    private long AUTORIZACIONES_SEMANAS_A;
    private String AUTORIZACIONES_HONO;
    private String AUTORIZACIONES_TIPODOC;
    private String AUTORIZACIONES_ANEXO;
    private long AUTORIZACIONES_COBERTURA;
    private String AUTORIZACIONES_SUCURSAL;
    private String AUTORIZACIONES_TIPOEVO;
    private long AUTORIZACIONES_PROBON;
    private String AUTORIZACIONES_IPS;
    private long AUTORIZACIONES_TEVOLU;
    private long AUTORIZACIONES_TIPO_CAL;
    private long AUTORIZACIONES_INTERVE;
    private String AUTORIZACIONES_NIVEL;
    private long AUTORIZACIONES_NUMDIAS;
    private long AUTORIZACIONES_OBJETA;
    private Float AUTORIZACIONES_NBONOS;
    private String AUTORIZACIONES_HORARTA;
    private String AUTORIZACIONES_PRIORIDAD;
    private String AUTORIZACIONES_FECRTA;
    private String AUTORIZACIONES_FECHA_SOLICITUD;
    private String AUTORIZACIONES_TEL_CONTACTO;
    private String AUTORIZACIONES_CIU_CONTACTO;
    private String AUTORIZACIONES_CODCAUSAL;
    private String AUTORIZACIONES_RTA;
    private String AUTORIZACIONES_DOCUENT;
    private String AUTORIZACIONES_ATTACH;
    private Date AUTORIZACIONES_FECHA_REC_CNA;
    private String AUTORIZACIONES_CAMBIO_PLAN;
    private long AUTORIZACIONES_CODIGO_REFERENCIA;
    private String AUTORIZACIONES_VIGFIN;
    private String AUTORIZACIONES_SEXO;
    private String AUTORIZACIONES_DERECHO_MATERNIDAD;
    private String AUTORIZACIONES_BEBE_GESTANTE;
    private int AUTORIZACIONES_ESTADO_ORDEN;
    private String AUTORIZACIONES_PRODUCTO_CRUZADO;
    private String AUTORIZACIONES_TIPO_AUTORIZACION;
    private String NUMERO_FUAI;
    private long AUTORIZACIONES_TIEMPO;
    private String AUTORIZACIONES_OBSER_CNA;
    private String AUTORIZACIONES_ESPECIALES;
    private long AUTORIZACIONES_NUMCONSULTA;
    private String AUTORIZACIONES_CORR_REMITE;
    private String AUTORIZACIONES_FECHA_CIRUGIA;
    private long AUTORIZACIONES_PORC_COL_PRE;
    private String AUTORIZACIONES_EN_COLA;
    private String AUTORIZACIONES_MORA_OPTIMO;
    private int AUTORIZACIONES_TIPO_RECOBRO;
    private long AUTORIZACIONES_CONSECUTIVO_CTC;
    private String AUTORIZACIONES_IDOFICINA_CTC;
    private String AUTORIZACIONES_FEC_SOLUCION;
    private long AUTORIZACIONES_CARTA_CONSECUTIVO;
    private String AUTORIZACIONES_CARTA_ID_OFICINA;
    private String AUTORIZACIONES_INGRESO;
    private String AUTORIZACIONES_PROV_FAX;
    private String AUTORIZACIONES_OFI_IMPRIME;
    private String AUTORIZACIONES_TIPO_RECAUDO;
    private String AUTORIZACIONES_TUTELA;
    private String AUTORIZACIONES_PROV_ESPECIALIDAD;
    private String AUTORIZACIONES_NOM_MEDICO_INST;
    private String AUTORIZACIONES_FECHA_CITA;
    private String AUTORIZACIONES_HORA_CITA;
    private String AUTORIZACIONES_TEL_CONSULTORIO;
    private String AUTORIZACIONES_CAUSA_PARCIAL;
    private String USUARIO_ASIGNADO;
    private String ESTADO_CASO;
    private long AUTORIZACIONES_VALOR_FINAL;
    private String AUTORIZACIONES_NIVEL_AUTORIZADOR;
    private long AUTORIZACIONES_NUMERO_REMPLAZA;
    private String AUTORIZACIONES_ID_OFI_REMPLAZA;
    private long AUTORIZACIONES_CAJA_ACORCAR;
    private long AUTORIZACIONES_CAJA_COPAGO;
    private long AUTORIZACIONES_CAJA_MODERA;
    private String AUTORIZACIONES_CAJA_FECHA;
    private int AUTORIZACIONES_OFICINA_CAJA;
    private long AUTORIZACIONES_DIF_REMPLAZA;
    private String AUTORIZACIONES_TIPO_IPS;
    private String AUTORIZACIONES_IPS_HOSP;
    private long AUTORIZACIONES_NROCASOATEP;
    private String AUTORIZACIONES_OFIATEP;
    private int AUTORIZACIONES_ESTADO_ATEP;
    private double AUTORIZACIONES_AGE_NROCITA;
    private String AUTORIZACIONES_IPS_INTEGRADA;
    private String AUTORIZACIONES_TIPO_REMIPS;
    private String AUTORIZACIONES_TIPIDE_REMIPS;
    private String AUTORIZACIONES_NUMIDE_REMIPS;
    private String AUTORIZACIONES_TIPO_REMITENTE;
    private int AUTORIZACIONES_DIAS_IMPRESION;
    private double AUTORIZACIONES_NROCITA_IPS;
    private String AUTORIZACIONES_PAQUETE_PYP;
    private Date AUTORIZACIONES_FECHA_INGRESO;
    private Date AUTORIZACIONES_FECHA_EGRESO;
    private String AUTORIZACIONES_NUEVO_POS;
    private int AUTORIZACIONES_MESES_PRE;
    private double AUTORIZACIONES_NUMORDEN;
    private int AUTORIZACIONES_TIPO_ORDEN;
    private String AUTORIZACIONES_POSPURO;
    private String AUTORIZACIONES_PREPAGO_VIGENTE;
    private int AUTORIZACIONES_NROSOLICITUD;
    private long AUTORIZACIONES_NRO_MINSAL;
    private long VALOR_TECNICA;
    private long VALOR_PROVISION;
    private String VALORIZA;
    private boolean CIERRE_EVENTO;
    private int ID_ORIGEN_CANAL;
    private String CodMensajeSalud;
    private Date AUTORIZACIONES_FECHAORDENMEDICA;
    private long VALOR_DESCUENTOS;
    private long VALOR_NETO;
    private long PORCENTAJE_RECOBRO;
    private String FECHA_VALORIZACION;


    public Authorization() {
    }


    public long getAUTORIZACIONES_NUMERO() {
        return AUTORIZACIONES_NUMERO;
    }

    public void setAUTORIZACIONES_NUMERO(long AUTORIZACIONES_NUMERO) {
        this.AUTORIZACIONES_NUMERO = AUTORIZACIONES_NUMERO;
    }

    public String getID_OFICINA() {
        return ID_OFICINA;
    }

    public void setID_OFICINA(String ID_OFICINA) {
        this.ID_OFICINA = ID_OFICINA;
    }

    public int getCODTIPOS_SERVICIO() {
        return CODTIPOS_SERVICIO;
    }

    public void setCODTIPOS_SERVICIO(int CODTIPOS_SERVICIO) {
        this.CODTIPOS_SERVICIO = CODTIPOS_SERVICIO;
    }

    public String getNUMIDE() {
        return NUMIDE;
    }

    public void setNUMIDE(String NUMIDE) {
        this.NUMIDE = NUMIDE;
    }

    public String getTIPIDE() {
        return TIPIDE;
    }

    public void setTIPIDE(String TIPIDE) {
        this.TIPIDE = TIPIDE;
    }

    public String getNROCON() {
        return NROCON;
    }

    public void setNROCON(String NROCON) {
        this.NROCON = NROCON;
    }

    public int getNUMBEN() {
        return NUMBEN;
    }

    public void setNUMBEN(int NUMBEN) {
        this.NUMBEN = NUMBEN;
    }

    public String getAUTORIZACIONES_TIPMEDAUT() {
        return AUTORIZACIONES_TIPMEDAUT;
    }

    public void setAUTORIZACIONES_TIPMEDAUT(String AUTORIZACIONES_TIPMEDAUT) {
        this.AUTORIZACIONES_TIPMEDAUT = AUTORIZACIONES_TIPMEDAUT;
    }

    public long getAUTORIZACIONES_NITMEDAUT() {
        return AUTORIZACIONES_NITMEDAUT;
    }

    public void setAUTORIZACIONES_NITMEDAUT(long AUTORIZACIONES_NITMEDAUT) {
        this.AUTORIZACIONES_NITMEDAUT = AUTORIZACIONES_NITMEDAUT;
    }

    public String getCIUCOD() {
        return CIUCOD;
    }

    public void setCIUCOD(String CIUCOD) {
        this.CIUCOD = CIUCOD;
    }

    public String getIDDIAGNOSTICOS() {
        return IDDIAGNOSTICOS;
    }

    public void setIDDIAGNOSTICOS(String IDDIAGNOSTICOS) {
        this.IDDIAGNOSTICOS = IDDIAGNOSTICOS;
    }

    public String getIDORIGEN() {
        return IDORIGEN;
    }

    public void setIDORIGEN(String IDORIGEN) {
        this.IDORIGEN = IDORIGEN;
    }

    public String getAUTORIZACIONES_TIPINS() {
        return AUTORIZACIONES_TIPINS;
    }

    public void setAUTORIZACIONES_TIPINS(String AUTORIZACIONES_TIPINS) {
        this.AUTORIZACIONES_TIPINS = AUTORIZACIONES_TIPINS;
    }

    public long getAUTORIZACIONES_NUMIDEINS() {
        return AUTORIZACIONES_NUMIDEINS;
    }

    public void setAUTORIZACIONES_NUMIDEINS(long AUTORIZACIONES_NUMIDEINS) {
        this.AUTORIZACIONES_NUMIDEINS = AUTORIZACIONES_NUMIDEINS;
    }

    public long getAUTORIZACIONES_TIPCON() {
        return AUTORIZACIONES_TIPCON;
    }

    public void setAUTORIZACIONES_TIPCON(long AUTORIZACIONES_TIPCON) {
        this.AUTORIZACIONES_TIPCON = AUTORIZACIONES_TIPCON;
    }

    public String getAUTORIZACIONES_CORR_DIR() {
        return AUTORIZACIONES_CORR_DIR;
    }

    public void setAUTORIZACIONES_CORR_DIR(String AUTORIZACIONES_CORR_DIR) {
        this.AUTORIZACIONES_CORR_DIR = AUTORIZACIONES_CORR_DIR;
    }

    public String getAUTORIZACIONES_FECHA_EXPED() {
        return AUTORIZACIONES_FECHA_EXPED;
    }

    public void setAUTORIZACIONES_FECHA_EXPED(String AUTORIZACIONES_FECHA_EXPED) {
        this.AUTORIZACIONES_FECHA_EXPED = AUTORIZACIONES_FECHA_EXPED;
    }

    public String getAUTORIZACIONES_OBSER() {
        return AUTORIZACIONES_OBSER;
    }

    public void setAUTORIZACIONES_OBSER(String AUTORIZACIONES_OBSER) {
        this.AUTORIZACIONES_OBSER = AUTORIZACIONES_OBSER;
    }

    public long getAUTORIZACIONES_CAURECHA() {
        return AUTORIZACIONES_CAURECHA;
    }

    public void setAUTORIZACIONES_CAURECHA(long AUTORIZACIONES_CAURECHA) {
        this.AUTORIZACIONES_CAURECHA = AUTORIZACIONES_CAURECHA;
    }

    public String getAUTORIZACIONES_FECHA_ESTADO() {
        return AUTORIZACIONES_FECHA_ESTADO;
    }

    public void setAUTORIZACIONES_FECHA_ESTADO(String AUTORIZACIONES_FECHA_ESTADO) {
        this.AUTORIZACIONES_FECHA_ESTADO = AUTORIZACIONES_FECHA_ESTADO;
    }

    public long getAUTORIZACIONES_ESTADO() {
        return AUTORIZACIONES_ESTADO;
    }

    public void setAUTORIZACIONES_ESTADO(long AUTORIZACIONES_ESTADO) {
        this.AUTORIZACIONES_ESTADO = AUTORIZACIONES_ESTADO;
    }

    public String getAUTORIZACIONES_PROINS() {
        return AUTORIZACIONES_PROINS;
    }

    public void setAUTORIZACIONES_PROINS(String AUTORIZACIONES_PROINS) {
        this.AUTORIZACIONES_PROINS = AUTORIZACIONES_PROINS;
    }

    public String getAUTORIZACIONES_PLANORD() {
        return AUTORIZACIONES_PLANORD;
    }

    public void setAUTORIZACIONES_PLANORD(String AUTORIZACIONES_PLANORD) {
        this.AUTORIZACIONES_PLANORD = AUTORIZACIONES_PLANORD;
    }

    public long getAUTORIZACIONES_VALOR() {
        return AUTORIZACIONES_VALOR;
    }

    public void setAUTORIZACIONES_VALOR(long AUTORIZACIONES_VALOR) {
        this.AUTORIZACIONES_VALOR = AUTORIZACIONES_VALOR;
    }

    public long getAUTORIZACIONES_VALOR_TOTAL() {
        return AUTORIZACIONES_VALOR_TOTAL;
    }

    public void setAUTORIZACIONES_VALOR_TOTAL(long AUTORIZACIONES_VALOR_TOTAL) {
        this.AUTORIZACIONES_VALOR_TOTAL = AUTORIZACIONES_VALOR_TOTAL;
    }

    public String getAUTORIZACIONES_RESPO() {
        return AUTORIZACIONES_RESPO;
    }

    public void setAUTORIZACIONES_RESPO(String AUTORIZACIONES_RESPO) {
        this.AUTORIZACIONES_RESPO = AUTORIZACIONES_RESPO;
    }

    public String getAUTORIZACIONES_FECHA_RADICA() {
        return AUTORIZACIONES_FECHA_RADICA;
    }

    public void setAUTORIZACIONES_FECHA_RADICA(String AUTORIZACIONES_FECHA_RADICA) {
        this.AUTORIZACIONES_FECHA_RADICA = AUTORIZACIONES_FECHA_RADICA;
    }

    public long getAUTORIZACIONES_CODOBSERV() {
        return AUTORIZACIONES_CODOBSERV;
    }

    public void setAUTORIZACIONES_CODOBSERV(long AUTORIZACIONES_CODOBSERV) {
        this.AUTORIZACIONES_CODOBSERV = AUTORIZACIONES_CODOBSERV;
    }

    public long getAUTORIZACIONES_COPAGO() {
        return AUTORIZACIONES_COPAGO;
    }

    public void setAUTORIZACIONES_COPAGO(long AUTORIZACIONES_COPAGO) {
        this.AUTORIZACIONES_COPAGO = AUTORIZACIONES_COPAGO;
    }

    public long getAUTORIZACIONES_MODERA() {
        return AUTORIZACIONES_MODERA;
    }

    public void setAUTORIZACIONES_MODERA(long AUTORIZACIONES_MODERA) {
        this.AUTORIZACIONES_MODERA = AUTORIZACIONES_MODERA;
    }

    public long getAUTORIZACIONES_SEMANAS() {
        return AUTORIZACIONES_SEMANAS;
    }

    public void setAUTORIZACIONES_SEMANAS(long AUTORIZACIONES_SEMANAS) {
        this.AUTORIZACIONES_SEMANAS = AUTORIZACIONES_SEMANAS;
    }

    public String getAUTORIZACIONES_ESTRATO() {
        return AUTORIZACIONES_ESTRATO;
    }

    public void setAUTORIZACIONES_ESTRATO(String AUTORIZACIONES_ESTRATO) {
        this.AUTORIZACIONES_ESTRATO = AUTORIZACIONES_ESTRATO;
    }

    public String getAUTORIZACIONES_FECHA_ANULA() {
        return AUTORIZACIONES_FECHA_ANULA;
    }

    public void setAUTORIZACIONES_FECHA_ANULA(String AUTORIZACIONES_FECHA_ANULA) {
        this.AUTORIZACIONES_FECHA_ANULA = AUTORIZACIONES_FECHA_ANULA;
    }

    public String getAUTORIZACIONES_ANULACION() {
        return AUTORIZACIONES_ANULACION;
    }

    public void setAUTORIZACIONES_ANULACION(String AUTORIZACIONES_ANULACION) {
        this.AUTORIZACIONES_ANULACION = AUTORIZACIONES_ANULACION;
    }

    public String getAUTORIZACIONES_IPSPRESTA() {
        return AUTORIZACIONES_IPSPRESTA;
    }

    public void setAUTORIZACIONES_IPSPRESTA(String AUTORIZACIONES_IPSPRESTA) {
        this.AUTORIZACIONES_IPSPRESTA = AUTORIZACIONES_IPSPRESTA;
    }

    public String getAUTORIZACIONES_IPSEXPIDE() {
        return AUTORIZACIONES_IPSEXPIDE;
    }

    public void setAUTORIZACIONES_IPSEXPIDE(String AUTORIZACIONES_IPSEXPIDE) {
        this.AUTORIZACIONES_IPSEXPIDE = AUTORIZACIONES_IPSEXPIDE;
    }

    public String getAUTORIZACIONES_HORARAD() {
        return AUTORIZACIONES_HORARAD;
    }

    public void setAUTORIZACIONES_HORARAD(String AUTORIZACIONES_HORARAD) {
        this.AUTORIZACIONES_HORARAD = AUTORIZACIONES_HORARAD;
    }

    public String getAUTORIZACIONES_ESTANCIA() {
        return AUTORIZACIONES_ESTANCIA;
    }

    public void setAUTORIZACIONES_ESTANCIA(String AUTORIZACIONES_ESTANCIA) {
        this.AUTORIZACIONES_ESTANCIA = AUTORIZACIONES_ESTANCIA;
    }

    public long getAUTORIZACIONES_TIPOATEN() {
        return AUTORIZACIONES_TIPOATEN;
    }

    public void setAUTORIZACIONES_TIPOATEN(long AUTORIZACIONES_TIPOATEN) {
        this.AUTORIZACIONES_TIPOATEN = AUTORIZACIONES_TIPOATEN;
    }

    public long getAUTORIZACIONES_CLASEATEN() {
        return AUTORIZACIONES_CLASEATEN;
    }

    public void setAUTORIZACIONES_CLASEATEN(long AUTORIZACIONES_CLASEATEN) {
        this.AUTORIZACIONES_CLASEATEN = AUTORIZACIONES_CLASEATEN;
    }

    public long getAUTORIZACIONES_CAUANULA() {
        return AUTORIZACIONES_CAUANULA;
    }

    public void setAUTORIZACIONES_CAUANULA(long AUTORIZACIONES_CAUANULA) {
        this.AUTORIZACIONES_CAUANULA = AUTORIZACIONES_CAUANULA;
    }

    public String getAUTORIZACIONES_COMPLEMENTO() {
        return AUTORIZACIONES_COMPLEMENTO;
    }

    public void setAUTORIZACIONES_COMPLEMENTO(String AUTORIZACIONES_COMPLEMENTO) {
        this.AUTORIZACIONES_COMPLEMENTO = AUTORIZACIONES_COMPLEMENTO;
    }

    public long getAUTORIZACIONES_ACORCAR() {
        return AUTORIZACIONES_ACORCAR;
    }

    public void setAUTORIZACIONES_ACORCAR(long AUTORIZACIONES_ACORCAR) {
        this.AUTORIZACIONES_ACORCAR = AUTORIZACIONES_ACORCAR;
    }

    public String getAUTORIZACIONES_IMPRESA() {
        return AUTORIZACIONES_IMPRESA;
    }

    public void setAUTORIZACIONES_IMPRESA(String AUTORIZACIONES_IMPRESA) {
        this.AUTORIZACIONES_IMPRESA = AUTORIZACIONES_IMPRESA;
    }

    public long getAUTORIZACIONES_PRO_ACOR_A() {
        return AUTORIZACIONES_PRO_ACOR_A;
    }

    public void setAUTORIZACIONES_PRO_ACOR_A(long AUTORIZACIONES_PRO_ACOR_A) {
        this.AUTORIZACIONES_PRO_ACOR_A = AUTORIZACIONES_PRO_ACOR_A;
    }

    public long getAUTORIZACIONES_SEMANAS_A() {
        return AUTORIZACIONES_SEMANAS_A;
    }

    public void setAUTORIZACIONES_SEMANAS_A(long AUTORIZACIONES_SEMANAS_A) {
        this.AUTORIZACIONES_SEMANAS_A = AUTORIZACIONES_SEMANAS_A;
    }

    public String getAUTORIZACIONES_HONO() {
        return AUTORIZACIONES_HONO;
    }

    public void setAUTORIZACIONES_HONO(String AUTORIZACIONES_HONO) {
        this.AUTORIZACIONES_HONO = AUTORIZACIONES_HONO;
    }

    public String getAUTORIZACIONES_TIPODOC() {
        return AUTORIZACIONES_TIPODOC;
    }

    public void setAUTORIZACIONES_TIPODOC(String AUTORIZACIONES_TIPODOC) {
        this.AUTORIZACIONES_TIPODOC = AUTORIZACIONES_TIPODOC;
    }

    public String getAUTORIZACIONES_ANEXO() {
        return AUTORIZACIONES_ANEXO;
    }

    public void setAUTORIZACIONES_ANEXO(String AUTORIZACIONES_ANEXO) {
        this.AUTORIZACIONES_ANEXO = AUTORIZACIONES_ANEXO;
    }

    public long getAUTORIZACIONES_COBERTURA() {
        return AUTORIZACIONES_COBERTURA;
    }

    public void setAUTORIZACIONES_COBERTURA(long AUTORIZACIONES_COBERTURA) {
        this.AUTORIZACIONES_COBERTURA = AUTORIZACIONES_COBERTURA;
    }

    public String getAUTORIZACIONES_SUCURSAL() {
        return AUTORIZACIONES_SUCURSAL;
    }

    public void setAUTORIZACIONES_SUCURSAL(String AUTORIZACIONES_SUCURSAL) {
        this.AUTORIZACIONES_SUCURSAL = AUTORIZACIONES_SUCURSAL;
    }

    public String getAUTORIZACIONES_TIPOEVO() {
        return AUTORIZACIONES_TIPOEVO;
    }

    public void setAUTORIZACIONES_TIPOEVO(String AUTORIZACIONES_TIPOEVO) {
        this.AUTORIZACIONES_TIPOEVO = AUTORIZACIONES_TIPOEVO;
    }

    public long getAUTORIZACIONES_PROBON() {
        return AUTORIZACIONES_PROBON;
    }

    public void setAUTORIZACIONES_PROBON(long AUTORIZACIONES_PROBON) {
        this.AUTORIZACIONES_PROBON = AUTORIZACIONES_PROBON;
    }

    public String getAUTORIZACIONES_IPS() {
        return AUTORIZACIONES_IPS;
    }

    public void setAUTORIZACIONES_IPS(String AUTORIZACIONES_IPS) {
        this.AUTORIZACIONES_IPS = AUTORIZACIONES_IPS;
    }

    public long getAUTORIZACIONES_TEVOLU() {
        return AUTORIZACIONES_TEVOLU;
    }

    public void setAUTORIZACIONES_TEVOLU(long AUTORIZACIONES_TEVOLU) {
        this.AUTORIZACIONES_TEVOLU = AUTORIZACIONES_TEVOLU;
    }

    public long getAUTORIZACIONES_TIPO_CAL() {
        return AUTORIZACIONES_TIPO_CAL;
    }

    public void setAUTORIZACIONES_TIPO_CAL(long AUTORIZACIONES_TIPO_CAL) {
        this.AUTORIZACIONES_TIPO_CAL = AUTORIZACIONES_TIPO_CAL;
    }

    public long getAUTORIZACIONES_INTERVE() {
        return AUTORIZACIONES_INTERVE;
    }

    public void setAUTORIZACIONES_INTERVE(long AUTORIZACIONES_INTERVE) {
        this.AUTORIZACIONES_INTERVE = AUTORIZACIONES_INTERVE;
    }

    public String getAUTORIZACIONES_NIVEL() {
        return AUTORIZACIONES_NIVEL;
    }

    public void setAUTORIZACIONES_NIVEL(String AUTORIZACIONES_NIVEL) {
        this.AUTORIZACIONES_NIVEL = AUTORIZACIONES_NIVEL;
    }

    public long getAUTORIZACIONES_NUMDIAS() {
        return AUTORIZACIONES_NUMDIAS;
    }

    public void setAUTORIZACIONES_NUMDIAS(long AUTORIZACIONES_NUMDIAS) {
        this.AUTORIZACIONES_NUMDIAS = AUTORIZACIONES_NUMDIAS;
    }

    public long getAUTORIZACIONES_OBJETA() {
        return AUTORIZACIONES_OBJETA;
    }

    public void setAUTORIZACIONES_OBJETA(long AUTORIZACIONES_OBJETA) {
        this.AUTORIZACIONES_OBJETA = AUTORIZACIONES_OBJETA;
    }

    public Float getAUTORIZACIONES_NBONOS() {
        return AUTORIZACIONES_NBONOS;
    }

    public void setAUTORIZACIONES_NBONOS(Float AUTORIZACIONES_NBONOS) {
        this.AUTORIZACIONES_NBONOS = AUTORIZACIONES_NBONOS;
    }

    public String getAUTORIZACIONES_HORARTA() {
        return AUTORIZACIONES_HORARTA;
    }

    public void setAUTORIZACIONES_HORARTA(String AUTORIZACIONES_HORARTA) {
        this.AUTORIZACIONES_HORARTA = AUTORIZACIONES_HORARTA;
    }

    public String getAUTORIZACIONES_PRIORIDAD() {
        return AUTORIZACIONES_PRIORIDAD;
    }

    public void setAUTORIZACIONES_PRIORIDAD(String AUTORIZACIONES_PRIORIDAD) {
        this.AUTORIZACIONES_PRIORIDAD = AUTORIZACIONES_PRIORIDAD;
    }

    public String getAUTORIZACIONES_FECRTA() {
        return AUTORIZACIONES_FECRTA;
    }

    public void setAUTORIZACIONES_FECRTA(String AUTORIZACIONES_FECRTA) {
        this.AUTORIZACIONES_FECRTA = AUTORIZACIONES_FECRTA;
    }

    public String getAUTORIZACIONES_FECHA_SOLICITUD() {
        return AUTORIZACIONES_FECHA_SOLICITUD;
    }

    public void setAUTORIZACIONES_FECHA_SOLICITUD(String AUTORIZACIONES_FECHA_SOLICITUD) {
        this.AUTORIZACIONES_FECHA_SOLICITUD = AUTORIZACIONES_FECHA_SOLICITUD;
    }

    public String getAUTORIZACIONES_TEL_CONTACTO() {
        return AUTORIZACIONES_TEL_CONTACTO;
    }

    public void setAUTORIZACIONES_TEL_CONTACTO(String AUTORIZACIONES_TEL_CONTACTO) {
        this.AUTORIZACIONES_TEL_CONTACTO = AUTORIZACIONES_TEL_CONTACTO;
    }

    public String getAUTORIZACIONES_CIU_CONTACTO() {
        return AUTORIZACIONES_CIU_CONTACTO;
    }

    public void setAUTORIZACIONES_CIU_CONTACTO(String AUTORIZACIONES_CIU_CONTACTO) {
        this.AUTORIZACIONES_CIU_CONTACTO = AUTORIZACIONES_CIU_CONTACTO;
    }

    public String getAUTORIZACIONES_CODCAUSAL() {
        return AUTORIZACIONES_CODCAUSAL;
    }

    public void setAUTORIZACIONES_CODCAUSAL(String AUTORIZACIONES_CODCAUSAL) {
        this.AUTORIZACIONES_CODCAUSAL = AUTORIZACIONES_CODCAUSAL;
    }

    public String getAUTORIZACIONES_RTA() {
        return AUTORIZACIONES_RTA;
    }

    public void setAUTORIZACIONES_RTA(String AUTORIZACIONES_RTA) {
        this.AUTORIZACIONES_RTA = AUTORIZACIONES_RTA;
    }

    public String getAUTORIZACIONES_DOCUENT() {
        return AUTORIZACIONES_DOCUENT;
    }

    public void setAUTORIZACIONES_DOCUENT(String AUTORIZACIONES_DOCUENT) {
        this.AUTORIZACIONES_DOCUENT = AUTORIZACIONES_DOCUENT;
    }

    public String getAUTORIZACIONES_ATTACH() {
        return AUTORIZACIONES_ATTACH;
    }

    public void setAUTORIZACIONES_ATTACH(String AUTORIZACIONES_ATTACH) {
        this.AUTORIZACIONES_ATTACH = AUTORIZACIONES_ATTACH;
    }

    public Date getAUTORIZACIONES_FECHA_REC_CNA() {
        return AUTORIZACIONES_FECHA_REC_CNA;
    }

    public void setAUTORIZACIONES_FECHA_REC_CNA(Date AUTORIZACIONES_FECHA_REC_CNA) {
        this.AUTORIZACIONES_FECHA_REC_CNA = AUTORIZACIONES_FECHA_REC_CNA;
    }

    public String getAUTORIZACIONES_CAMBIO_PLAN() {
        return AUTORIZACIONES_CAMBIO_PLAN;
    }

    public void setAUTORIZACIONES_CAMBIO_PLAN(String AUTORIZACIONES_CAMBIO_PLAN) {
        this.AUTORIZACIONES_CAMBIO_PLAN = AUTORIZACIONES_CAMBIO_PLAN;
    }

    public long getAUTORIZACIONES_CODIGO_REFERENCIA() {
        return AUTORIZACIONES_CODIGO_REFERENCIA;
    }

    public void setAUTORIZACIONES_CODIGO_REFERENCIA(long AUTORIZACIONES_CODIGO_REFERENCIA) {
        this.AUTORIZACIONES_CODIGO_REFERENCIA = AUTORIZACIONES_CODIGO_REFERENCIA;
    }

    public String getAUTORIZACIONES_VIGFIN() {
        return AUTORIZACIONES_VIGFIN;
    }

    public void setAUTORIZACIONES_VIGFIN(String AUTORIZACIONES_VIGFIN) {
        this.AUTORIZACIONES_VIGFIN = AUTORIZACIONES_VIGFIN;
    }

    public String getAUTORIZACIONES_SEXO() {
        return AUTORIZACIONES_SEXO;
    }

    public void setAUTORIZACIONES_SEXO(String AUTORIZACIONES_SEXO) {
        this.AUTORIZACIONES_SEXO = AUTORIZACIONES_SEXO;
    }

    public String getAUTORIZACIONES_DERECHO_MATERNIDAD() {
        return AUTORIZACIONES_DERECHO_MATERNIDAD;
    }

    public void setAUTORIZACIONES_DERECHO_MATERNIDAD(String AUTORIZACIONES_DERECHO_MATERNIDAD) {
        this.AUTORIZACIONES_DERECHO_MATERNIDAD = AUTORIZACIONES_DERECHO_MATERNIDAD;
    }

    public String getAUTORIZACIONES_BEBE_GESTANTE() {
        return AUTORIZACIONES_BEBE_GESTANTE;
    }

    public void setAUTORIZACIONES_BEBE_GESTANTE(String AUTORIZACIONES_BEBE_GESTANTE) {
        this.AUTORIZACIONES_BEBE_GESTANTE = AUTORIZACIONES_BEBE_GESTANTE;
    }

    public int getAUTORIZACIONES_ESTADO_ORDEN() {
        return AUTORIZACIONES_ESTADO_ORDEN;
    }

    public void setAUTORIZACIONES_ESTADO_ORDEN(int AUTORIZACIONES_ESTADO_ORDEN) {
        this.AUTORIZACIONES_ESTADO_ORDEN = AUTORIZACIONES_ESTADO_ORDEN;
    }

    public String getAUTORIZACIONES_PRODUCTO_CRUZADO() {
        return AUTORIZACIONES_PRODUCTO_CRUZADO;
    }

    public void setAUTORIZACIONES_PRODUCTO_CRUZADO(String AUTORIZACIONES_PRODUCTO_CRUZADO) {
        this.AUTORIZACIONES_PRODUCTO_CRUZADO = AUTORIZACIONES_PRODUCTO_CRUZADO;
    }

    public String getAUTORIZACIONES_TIPO_AUTORIZACION() {
        return AUTORIZACIONES_TIPO_AUTORIZACION;
    }

    public void setAUTORIZACIONES_TIPO_AUTORIZACION(String AUTORIZACIONES_TIPO_AUTORIZACION) {
        this.AUTORIZACIONES_TIPO_AUTORIZACION = AUTORIZACIONES_TIPO_AUTORIZACION;
    }

    public String getNUMERO_FUAI() {
        return NUMERO_FUAI;
    }

    public void setNUMERO_FUAI(String NUMERO_FUAI) {
        this.NUMERO_FUAI = NUMERO_FUAI;
    }

    public long getAUTORIZACIONES_TIEMPO() {
        return AUTORIZACIONES_TIEMPO;
    }

    public void setAUTORIZACIONES_TIEMPO(long AUTORIZACIONES_TIEMPO) {
        this.AUTORIZACIONES_TIEMPO = AUTORIZACIONES_TIEMPO;
    }

    public String getAUTORIZACIONES_OBSER_CNA() {
        return AUTORIZACIONES_OBSER_CNA;
    }

    public void setAUTORIZACIONES_OBSER_CNA(String AUTORIZACIONES_OBSER_CNA) {
        this.AUTORIZACIONES_OBSER_CNA = AUTORIZACIONES_OBSER_CNA;
    }

    public String getAUTORIZACIONES_ESPECIALES() {
        return AUTORIZACIONES_ESPECIALES;
    }

    public void setAUTORIZACIONES_ESPECIALES(String AUTORIZACIONES_ESPECIALES) {
        this.AUTORIZACIONES_ESPECIALES = AUTORIZACIONES_ESPECIALES;
    }

    public long getAUTORIZACIONES_NUMCONSULTA() {
        return AUTORIZACIONES_NUMCONSULTA;
    }

    public void setAUTORIZACIONES_NUMCONSULTA(long AUTORIZACIONES_NUMCONSULTA) {
        this.AUTORIZACIONES_NUMCONSULTA = AUTORIZACIONES_NUMCONSULTA;
    }

    public String getAUTORIZACIONES_CORR_REMITE() {
        return AUTORIZACIONES_CORR_REMITE;
    }

    public void setAUTORIZACIONES_CORR_REMITE(String AUTORIZACIONES_CORR_REMITE) {
        this.AUTORIZACIONES_CORR_REMITE = AUTORIZACIONES_CORR_REMITE;
    }

    public String getAUTORIZACIONES_FECHA_CIRUGIA() {
        return AUTORIZACIONES_FECHA_CIRUGIA;
    }

    public void setAUTORIZACIONES_FECHA_CIRUGIA(String AUTORIZACIONES_FECHA_CIRUGIA) {
        this.AUTORIZACIONES_FECHA_CIRUGIA = AUTORIZACIONES_FECHA_CIRUGIA;
    }

    public long getAUTORIZACIONES_PORC_COL_PRE() {
        return AUTORIZACIONES_PORC_COL_PRE;
    }

    public void setAUTORIZACIONES_PORC_COL_PRE(long AUTORIZACIONES_PORC_COL_PRE) {
        this.AUTORIZACIONES_PORC_COL_PRE = AUTORIZACIONES_PORC_COL_PRE;
    }

    public String getAUTORIZACIONES_EN_COLA() {
        return AUTORIZACIONES_EN_COLA;
    }

    public void setAUTORIZACIONES_EN_COLA(String AUTORIZACIONES_EN_COLA) {
        this.AUTORIZACIONES_EN_COLA = AUTORIZACIONES_EN_COLA;
    }

    public String getAUTORIZACIONES_MORA_OPTIMO() {
        return AUTORIZACIONES_MORA_OPTIMO;
    }

    public void setAUTORIZACIONES_MORA_OPTIMO(String AUTORIZACIONES_MORA_OPTIMO) {
        this.AUTORIZACIONES_MORA_OPTIMO = AUTORIZACIONES_MORA_OPTIMO;
    }

    public int getAUTORIZACIONES_TIPO_RECOBRO() {
        return AUTORIZACIONES_TIPO_RECOBRO;
    }

    public void setAUTORIZACIONES_TIPO_RECOBRO(int AUTORIZACIONES_TIPO_RECOBRO) {
        this.AUTORIZACIONES_TIPO_RECOBRO = AUTORIZACIONES_TIPO_RECOBRO;
    }

    public long getAUTORIZACIONES_CONSECUTIVO_CTC() {
        return AUTORIZACIONES_CONSECUTIVO_CTC;
    }

    public void setAUTORIZACIONES_CONSECUTIVO_CTC(long AUTORIZACIONES_CONSECUTIVO_CTC) {
        this.AUTORIZACIONES_CONSECUTIVO_CTC = AUTORIZACIONES_CONSECUTIVO_CTC;
    }

    public String getAUTORIZACIONES_IDOFICINA_CTC() {
        return AUTORIZACIONES_IDOFICINA_CTC;
    }

    public void setAUTORIZACIONES_IDOFICINA_CTC(String AUTORIZACIONES_IDOFICINA_CTC) {
        this.AUTORIZACIONES_IDOFICINA_CTC = AUTORIZACIONES_IDOFICINA_CTC;
    }

    public String getAUTORIZACIONES_FEC_SOLUCION() {
        return AUTORIZACIONES_FEC_SOLUCION;
    }

    public void setAUTORIZACIONES_FEC_SOLUCION(String AUTORIZACIONES_FEC_SOLUCION) {
        this.AUTORIZACIONES_FEC_SOLUCION = AUTORIZACIONES_FEC_SOLUCION;
    }

    public long getAUTORIZACIONES_CARTA_CONSECUTIVO() {
        return AUTORIZACIONES_CARTA_CONSECUTIVO;
    }

    public void setAUTORIZACIONES_CARTA_CONSECUTIVO(long AUTORIZACIONES_CARTA_CONSECUTIVO) {
        this.AUTORIZACIONES_CARTA_CONSECUTIVO = AUTORIZACIONES_CARTA_CONSECUTIVO;
    }

    public String getAUTORIZACIONES_CARTA_ID_OFICINA() {
        return AUTORIZACIONES_CARTA_ID_OFICINA;
    }

    public void setAUTORIZACIONES_CARTA_ID_OFICINA(String AUTORIZACIONES_CARTA_ID_OFICINA) {
        this.AUTORIZACIONES_CARTA_ID_OFICINA = AUTORIZACIONES_CARTA_ID_OFICINA;
    }

    public String getAUTORIZACIONES_INGRESO() {
        return AUTORIZACIONES_INGRESO;
    }

    public void setAUTORIZACIONES_INGRESO(String AUTORIZACIONES_INGRESO) {
        this.AUTORIZACIONES_INGRESO = AUTORIZACIONES_INGRESO;
    }

    public String getAUTORIZACIONES_PROV_FAX() {
        return AUTORIZACIONES_PROV_FAX;
    }

    public void setAUTORIZACIONES_PROV_FAX(String AUTORIZACIONES_PROV_FAX) {
        this.AUTORIZACIONES_PROV_FAX = AUTORIZACIONES_PROV_FAX;
    }

    public String getAUTORIZACIONES_OFI_IMPRIME() {
        return AUTORIZACIONES_OFI_IMPRIME;
    }

    public void setAUTORIZACIONES_OFI_IMPRIME(String AUTORIZACIONES_OFI_IMPRIME) {
        this.AUTORIZACIONES_OFI_IMPRIME = AUTORIZACIONES_OFI_IMPRIME;
    }

    public String getAUTORIZACIONES_TIPO_RECAUDO() {
        return AUTORIZACIONES_TIPO_RECAUDO;
    }

    public void setAUTORIZACIONES_TIPO_RECAUDO(String AUTORIZACIONES_TIPO_RECAUDO) {
        this.AUTORIZACIONES_TIPO_RECAUDO = AUTORIZACIONES_TIPO_RECAUDO;
    }

    public String getAUTORIZACIONES_TUTELA() {
        return AUTORIZACIONES_TUTELA;
    }

    public void setAUTORIZACIONES_TUTELA(String AUTORIZACIONES_TUTELA) {
        this.AUTORIZACIONES_TUTELA = AUTORIZACIONES_TUTELA;
    }

    public String getAUTORIZACIONES_PROV_ESPECIALIDAD() {
        return AUTORIZACIONES_PROV_ESPECIALIDAD;
    }

    public void setAUTORIZACIONES_PROV_ESPECIALIDAD(String AUTORIZACIONES_PROV_ESPECIALIDAD) {
        this.AUTORIZACIONES_PROV_ESPECIALIDAD = AUTORIZACIONES_PROV_ESPECIALIDAD;
    }

    public String getAUTORIZACIONES_NOM_MEDICO_INST() {
        return AUTORIZACIONES_NOM_MEDICO_INST;
    }

    public void setAUTORIZACIONES_NOM_MEDICO_INST(String AUTORIZACIONES_NOM_MEDICO_INST) {
        this.AUTORIZACIONES_NOM_MEDICO_INST = AUTORIZACIONES_NOM_MEDICO_INST;
    }

    public String getAUTORIZACIONES_FECHA_CITA() {
        return AUTORIZACIONES_FECHA_CITA;
    }

    public void setAUTORIZACIONES_FECHA_CITA(String AUTORIZACIONES_FECHA_CITA) {
        this.AUTORIZACIONES_FECHA_CITA = AUTORIZACIONES_FECHA_CITA;
    }

    public String getAUTORIZACIONES_HORA_CITA() {
        return AUTORIZACIONES_HORA_CITA;
    }

    public void setAUTORIZACIONES_HORA_CITA(String AUTORIZACIONES_HORA_CITA) {
        this.AUTORIZACIONES_HORA_CITA = AUTORIZACIONES_HORA_CITA;
    }

    public String getAUTORIZACIONES_TEL_CONSULTORIO() {
        return AUTORIZACIONES_TEL_CONSULTORIO;
    }

    public void setAUTORIZACIONES_TEL_CONSULTORIO(String AUTORIZACIONES_TEL_CONSULTORIO) {
        this.AUTORIZACIONES_TEL_CONSULTORIO = AUTORIZACIONES_TEL_CONSULTORIO;
    }

    public String getAUTORIZACIONES_CAUSA_PARCIAL() {
        return AUTORIZACIONES_CAUSA_PARCIAL;
    }

    public void setAUTORIZACIONES_CAUSA_PARCIAL(String AUTORIZACIONES_CAUSA_PARCIAL) {
        this.AUTORIZACIONES_CAUSA_PARCIAL = AUTORIZACIONES_CAUSA_PARCIAL;
    }

    public String getUSUARIO_ASIGNADO() {
        return USUARIO_ASIGNADO;
    }

    public void setUSUARIO_ASIGNADO(String USUARIO_ASIGNADO) {
        this.USUARIO_ASIGNADO = USUARIO_ASIGNADO;
    }

    public String getESTADO_CASO() {
        return ESTADO_CASO;
    }

    public void setESTADO_CASO(String ESTADO_CASO) {
        this.ESTADO_CASO = ESTADO_CASO;
    }

    public long getAUTORIZACIONES_VALOR_FINAL() {
        return AUTORIZACIONES_VALOR_FINAL;
    }

    public void setAUTORIZACIONES_VALOR_FINAL(long AUTORIZACIONES_VALOR_FINAL) {
        this.AUTORIZACIONES_VALOR_FINAL = AUTORIZACIONES_VALOR_FINAL;
    }

    public String getAUTORIZACIONES_NIVEL_AUTORIZADOR() {
        return AUTORIZACIONES_NIVEL_AUTORIZADOR;
    }

    public void setAUTORIZACIONES_NIVEL_AUTORIZADOR(String AUTORIZACIONES_NIVEL_AUTORIZADOR) {
        this.AUTORIZACIONES_NIVEL_AUTORIZADOR = AUTORIZACIONES_NIVEL_AUTORIZADOR;
    }

    public long getAUTORIZACIONES_NUMERO_REMPLAZA() {
        return AUTORIZACIONES_NUMERO_REMPLAZA;
    }

    public void setAUTORIZACIONES_NUMERO_REMPLAZA(long AUTORIZACIONES_NUMERO_REMPLAZA) {
        this.AUTORIZACIONES_NUMERO_REMPLAZA = AUTORIZACIONES_NUMERO_REMPLAZA;
    }

    public String getAUTORIZACIONES_ID_OFI_REMPLAZA() {
        return AUTORIZACIONES_ID_OFI_REMPLAZA;
    }

    public void setAUTORIZACIONES_ID_OFI_REMPLAZA(String AUTORIZACIONES_ID_OFI_REMPLAZA) {
        this.AUTORIZACIONES_ID_OFI_REMPLAZA = AUTORIZACIONES_ID_OFI_REMPLAZA;
    }

    public long getAUTORIZACIONES_CAJA_ACORCAR() {
        return AUTORIZACIONES_CAJA_ACORCAR;
    }

    public void setAUTORIZACIONES_CAJA_ACORCAR(long AUTORIZACIONES_CAJA_ACORCAR) {
        this.AUTORIZACIONES_CAJA_ACORCAR = AUTORIZACIONES_CAJA_ACORCAR;
    }

    public long getAUTORIZACIONES_CAJA_COPAGO() {
        return AUTORIZACIONES_CAJA_COPAGO;
    }

    public void setAUTORIZACIONES_CAJA_COPAGO(long AUTORIZACIONES_CAJA_COPAGO) {
        this.AUTORIZACIONES_CAJA_COPAGO = AUTORIZACIONES_CAJA_COPAGO;
    }

    public long getAUTORIZACIONES_CAJA_MODERA() {
        return AUTORIZACIONES_CAJA_MODERA;
    }

    public void setAUTORIZACIONES_CAJA_MODERA(long AUTORIZACIONES_CAJA_MODERA) {
        this.AUTORIZACIONES_CAJA_MODERA = AUTORIZACIONES_CAJA_MODERA;
    }

    public String getAUTORIZACIONES_CAJA_FECHA() {
        return AUTORIZACIONES_CAJA_FECHA;
    }

    public void setAUTORIZACIONES_CAJA_FECHA(String AUTORIZACIONES_CAJA_FECHA) {
        this.AUTORIZACIONES_CAJA_FECHA = AUTORIZACIONES_CAJA_FECHA;
    }

    public int getAUTORIZACIONES_OFICINA_CAJA() {
        return AUTORIZACIONES_OFICINA_CAJA;
    }

    public void setAUTORIZACIONES_OFICINA_CAJA(int AUTORIZACIONES_OFICINA_CAJA) {
        this.AUTORIZACIONES_OFICINA_CAJA = AUTORIZACIONES_OFICINA_CAJA;
    }

    public long getAUTORIZACIONES_DIF_REMPLAZA() {
        return AUTORIZACIONES_DIF_REMPLAZA;
    }

    public void setAUTORIZACIONES_DIF_REMPLAZA(long AUTORIZACIONES_DIF_REMPLAZA) {
        this.AUTORIZACIONES_DIF_REMPLAZA = AUTORIZACIONES_DIF_REMPLAZA;
    }

    public String getAUTORIZACIONES_TIPO_IPS() {
        return AUTORIZACIONES_TIPO_IPS;
    }

    public void setAUTORIZACIONES_TIPO_IPS(String AUTORIZACIONES_TIPO_IPS) {
        this.AUTORIZACIONES_TIPO_IPS = AUTORIZACIONES_TIPO_IPS;
    }

    public String getAUTORIZACIONES_IPS_HOSP() {
        return AUTORIZACIONES_IPS_HOSP;
    }

    public void setAUTORIZACIONES_IPS_HOSP(String AUTORIZACIONES_IPS_HOSP) {
        this.AUTORIZACIONES_IPS_HOSP = AUTORIZACIONES_IPS_HOSP;
    }

    public long getAUTORIZACIONES_NROCASOATEP() {
        return AUTORIZACIONES_NROCASOATEP;
    }

    public void setAUTORIZACIONES_NROCASOATEP(long AUTORIZACIONES_NROCASOATEP) {
        this.AUTORIZACIONES_NROCASOATEP = AUTORIZACIONES_NROCASOATEP;
    }

    public String getAUTORIZACIONES_OFIATEP() {
        return AUTORIZACIONES_OFIATEP;
    }

    public void setAUTORIZACIONES_OFIATEP(String AUTORIZACIONES_OFIATEP) {
        this.AUTORIZACIONES_OFIATEP = AUTORIZACIONES_OFIATEP;
    }

    public int getAUTORIZACIONES_ESTADO_ATEP() {
        return AUTORIZACIONES_ESTADO_ATEP;
    }

    public void setAUTORIZACIONES_ESTADO_ATEP(int AUTORIZACIONES_ESTADO_ATEP) {
        this.AUTORIZACIONES_ESTADO_ATEP = AUTORIZACIONES_ESTADO_ATEP;
    }

    public double getAUTORIZACIONES_AGE_NROCITA() {
        return AUTORIZACIONES_AGE_NROCITA;
    }

    public void setAUTORIZACIONES_AGE_NROCITA(double AUTORIZACIONES_AGE_NROCITA) {
        this.AUTORIZACIONES_AGE_NROCITA = AUTORIZACIONES_AGE_NROCITA;
    }

    public String getAUTORIZACIONES_IPS_INTEGRADA() {
        return AUTORIZACIONES_IPS_INTEGRADA;
    }

    public void setAUTORIZACIONES_IPS_INTEGRADA(String AUTORIZACIONES_IPS_INTEGRADA) {
        this.AUTORIZACIONES_IPS_INTEGRADA = AUTORIZACIONES_IPS_INTEGRADA;
    }

    public String getAUTORIZACIONES_TIPO_REMIPS() {
        return AUTORIZACIONES_TIPO_REMIPS;
    }

    public void setAUTORIZACIONES_TIPO_REMIPS(String AUTORIZACIONES_TIPO_REMIPS) {
        this.AUTORIZACIONES_TIPO_REMIPS = AUTORIZACIONES_TIPO_REMIPS;
    }

    public String getAUTORIZACIONES_TIPIDE_REMIPS() {
        return AUTORIZACIONES_TIPIDE_REMIPS;
    }

    public void setAUTORIZACIONES_TIPIDE_REMIPS(String AUTORIZACIONES_TIPIDE_REMIPS) {
        this.AUTORIZACIONES_TIPIDE_REMIPS = AUTORIZACIONES_TIPIDE_REMIPS;
    }

    public String getAUTORIZACIONES_NUMIDE_REMIPS() {
        return AUTORIZACIONES_NUMIDE_REMIPS;
    }

    public void setAUTORIZACIONES_NUMIDE_REMIPS(String AUTORIZACIONES_NUMIDE_REMIPS) {
        this.AUTORIZACIONES_NUMIDE_REMIPS = AUTORIZACIONES_NUMIDE_REMIPS;
    }

    public String getAUTORIZACIONES_TIPO_REMITENTE() {
        return AUTORIZACIONES_TIPO_REMITENTE;
    }

    public void setAUTORIZACIONES_TIPO_REMITENTE(String AUTORIZACIONES_TIPO_REMITENTE) {
        this.AUTORIZACIONES_TIPO_REMITENTE = AUTORIZACIONES_TIPO_REMITENTE;
    }

    public int getAUTORIZACIONES_DIAS_IMPRESION() {
        return AUTORIZACIONES_DIAS_IMPRESION;
    }

    public void setAUTORIZACIONES_DIAS_IMPRESION(int AUTORIZACIONES_DIAS_IMPRESION) {
        this.AUTORIZACIONES_DIAS_IMPRESION = AUTORIZACIONES_DIAS_IMPRESION;
    }

    public double getAUTORIZACIONES_NROCITA_IPS() {
        return AUTORIZACIONES_NROCITA_IPS;
    }

    public void setAUTORIZACIONES_NROCITA_IPS(double AUTORIZACIONES_NROCITA_IPS) {
        this.AUTORIZACIONES_NROCITA_IPS = AUTORIZACIONES_NROCITA_IPS;
    }

    public String getAUTORIZACIONES_PAQUETE_PYP() {
        return AUTORIZACIONES_PAQUETE_PYP;
    }

    public void setAUTORIZACIONES_PAQUETE_PYP(String AUTORIZACIONES_PAQUETE_PYP) {
        this.AUTORIZACIONES_PAQUETE_PYP = AUTORIZACIONES_PAQUETE_PYP;
    }

    public Date getAUTORIZACIONES_FECHA_INGRESO() {
        return AUTORIZACIONES_FECHA_INGRESO;
    }

    public void setAUTORIZACIONES_FECHA_INGRESO(Date AUTORIZACIONES_FECHA_INGRESO) {
        this.AUTORIZACIONES_FECHA_INGRESO = AUTORIZACIONES_FECHA_INGRESO;
    }

    public Date getAUTORIZACIONES_FECHA_EGRESO() {
        return AUTORIZACIONES_FECHA_EGRESO;
    }

    public void setAUTORIZACIONES_FECHA_EGRESO(Date AUTORIZACIONES_FECHA_EGRESO) {
        this.AUTORIZACIONES_FECHA_EGRESO = AUTORIZACIONES_FECHA_EGRESO;
    }

    public String getAUTORIZACIONES_NUEVO_POS() {
        return AUTORIZACIONES_NUEVO_POS;
    }

    public void setAUTORIZACIONES_NUEVO_POS(String AUTORIZACIONES_NUEVO_POS) {
        this.AUTORIZACIONES_NUEVO_POS = AUTORIZACIONES_NUEVO_POS;
    }

    public int getAUTORIZACIONES_MESES_PRE() {
        return AUTORIZACIONES_MESES_PRE;
    }

    public void setAUTORIZACIONES_MESES_PRE(int AUTORIZACIONES_MESES_PRE) {
        this.AUTORIZACIONES_MESES_PRE = AUTORIZACIONES_MESES_PRE;
    }

    public double getAUTORIZACIONES_NUMORDEN() {
        return AUTORIZACIONES_NUMORDEN;
    }

    public void setAUTORIZACIONES_NUMORDEN(double AUTORIZACIONES_NUMORDEN) {
        this.AUTORIZACIONES_NUMORDEN = AUTORIZACIONES_NUMORDEN;
    }

    public int getAUTORIZACIONES_TIPO_ORDEN() {
        return AUTORIZACIONES_TIPO_ORDEN;
    }

    public void setAUTORIZACIONES_TIPO_ORDEN(int AUTORIZACIONES_TIPO_ORDEN) {
        this.AUTORIZACIONES_TIPO_ORDEN = AUTORIZACIONES_TIPO_ORDEN;
    }

    public String getAUTORIZACIONES_POSPURO() {
        return AUTORIZACIONES_POSPURO;
    }

    public void setAUTORIZACIONES_POSPURO(String AUTORIZACIONES_POSPURO) {
        this.AUTORIZACIONES_POSPURO = AUTORIZACIONES_POSPURO;
    }

    public String getAUTORIZACIONES_PREPAGO_VIGENTE() {
        return AUTORIZACIONES_PREPAGO_VIGENTE;
    }

    public void setAUTORIZACIONES_PREPAGO_VIGENTE(String AUTORIZACIONES_PREPAGO_VIGENTE) {
        this.AUTORIZACIONES_PREPAGO_VIGENTE = AUTORIZACIONES_PREPAGO_VIGENTE;
    }

    public int getAUTORIZACIONES_NROSOLICITUD() {
        return AUTORIZACIONES_NROSOLICITUD;
    }

    public void setAUTORIZACIONES_NROSOLICITUD(int AUTORIZACIONES_NROSOLICITUD) {
        this.AUTORIZACIONES_NROSOLICITUD = AUTORIZACIONES_NROSOLICITUD;
    }

    public long getAUTORIZACIONES_NRO_MINSAL() {
        return AUTORIZACIONES_NRO_MINSAL;
    }

    public void setAUTORIZACIONES_NRO_MINSAL(long AUTORIZACIONES_NRO_MINSAL) {
        this.AUTORIZACIONES_NRO_MINSAL = AUTORIZACIONES_NRO_MINSAL;
    }

    public long getVALOR_TECNICA() {
        return VALOR_TECNICA;
    }

    public void setVALOR_TECNICA(long VALOR_TECNICA) {
        this.VALOR_TECNICA = VALOR_TECNICA;
    }

    public long getVALOR_PROVISION() {
        return VALOR_PROVISION;
    }

    public void setVALOR_PROVISION(long VALOR_PROVISION) {
        this.VALOR_PROVISION = VALOR_PROVISION;
    }

    public String getVALORIZA() {
        return VALORIZA;
    }

    public void setVALORIZA(String VALORIZA) {
        this.VALORIZA = VALORIZA;
    }

    public boolean isCIERRE_EVENTO() {
        return CIERRE_EVENTO;
    }

    public void setCIERRE_EVENTO(boolean CIERRE_EVENTO) {
        this.CIERRE_EVENTO = CIERRE_EVENTO;
    }

    public int getID_ORIGEN_CANAL() {
        return ID_ORIGEN_CANAL;
    }

    public void setID_ORIGEN_CANAL(int ID_ORIGEN_CANAL) {
        this.ID_ORIGEN_CANAL = ID_ORIGEN_CANAL;
    }

    public String getCodMensajeSalud() {
        return CodMensajeSalud;
    }

    public void setCodMensajeSalud(String codMensajeSalud) {
        CodMensajeSalud = codMensajeSalud;
    }

    public Date getAUTORIZACIONES_FECHAORDENMEDICA() {
        return AUTORIZACIONES_FECHAORDENMEDICA;
    }

    public void setAUTORIZACIONES_FECHAORDENMEDICA(Date AUTORIZACIONES_FECHAORDENMEDICA) {
        this.AUTORIZACIONES_FECHAORDENMEDICA = AUTORIZACIONES_FECHAORDENMEDICA;
    }

    public long getVALOR_DESCUENTOS() {
        return VALOR_DESCUENTOS;
    }

    public void setVALOR_DESCUENTOS(long VALOR_DESCUENTOS) {
        this.VALOR_DESCUENTOS = VALOR_DESCUENTOS;
    }

    public long getVALOR_NETO() {
        return VALOR_NETO;
    }

    public void setVALOR_NETO(long VALOR_NETO) {
        this.VALOR_NETO = VALOR_NETO;
    }

    public long getPORCENTAJE_RECOBRO() {
        return PORCENTAJE_RECOBRO;
    }

    public void setPORCENTAJE_RECOBRO(long PORCENTAJE_RECOBRO) {
        this.PORCENTAJE_RECOBRO = PORCENTAJE_RECOBRO;
    }

    public String getFECHA_VALORIZACION() {
        return FECHA_VALORIZACION;
    }

    public void setFECHA_VALORIZACION(String FECHA_VALORIZACION) {
        this.FECHA_VALORIZACION = FECHA_VALORIZACION;
    }

    @Override
    public String toString() {
        return "Authorization{" +
                "AUTORIZACIONES_NUMERO=" + AUTORIZACIONES_NUMERO +
                ", ID_OFICINA='" + ID_OFICINA + '\'' +
                ", CODTIPOS_SERVICIO=" + CODTIPOS_SERVICIO +
                ", NUMIDE='" + NUMIDE + '\'' +
                ", TIPIDE='" + TIPIDE + '\'' +
                ", NROCON='" + NROCON + '\'' +
                ", NUMBEN=" + NUMBEN +
                ", AUTORIZACIONES_TIPMEDAUT='" + AUTORIZACIONES_TIPMEDAUT + '\'' +
                ", AUTORIZACIONES_NITMEDAUT=" + AUTORIZACIONES_NITMEDAUT +
                ", CIUCOD='" + CIUCOD + '\'' +
                ", IDDIAGNOSTICOS='" + IDDIAGNOSTICOS + '\'' +
                ", IDORIGEN='" + IDORIGEN + '\'' +
                ", AUTORIZACIONES_TIPINS='" + AUTORIZACIONES_TIPINS + '\'' +
                ", AUTORIZACIONES_NUMIDEINS=" + AUTORIZACIONES_NUMIDEINS +
                ", AUTORIZACIONES_TIPCON=" + AUTORIZACIONES_TIPCON +
                ", AUTORIZACIONES_CORR_DIR='" + AUTORIZACIONES_CORR_DIR + '\'' +
                ", AUTORIZACIONES_FECHA_EXPED='" + AUTORIZACIONES_FECHA_EXPED + '\'' +
                ", AUTORIZACIONES_OBSER='" + AUTORIZACIONES_OBSER + '\'' +
                ", AUTORIZACIONES_CAURECHA=" + AUTORIZACIONES_CAURECHA +
                ", AUTORIZACIONES_FECHA_ESTADO='" + AUTORIZACIONES_FECHA_ESTADO + '\'' +
                ", AUTORIZACIONES_ESTADO=" + AUTORIZACIONES_ESTADO +
                ", AUTORIZACIONES_PROINS='" + AUTORIZACIONES_PROINS + '\'' +
                ", AUTORIZACIONES_PLANORD='" + AUTORIZACIONES_PLANORD + '\'' +
                ", AUTORIZACIONES_VALOR=" + AUTORIZACIONES_VALOR +
                ", AUTORIZACIONES_VALOR_TOTAL=" + AUTORIZACIONES_VALOR_TOTAL +
                ", AUTORIZACIONES_RESPO='" + AUTORIZACIONES_RESPO + '\'' +
                ", AUTORIZACIONES_FECHA_RADICA='" + AUTORIZACIONES_FECHA_RADICA + '\'' +
                ", AUTORIZACIONES_CODOBSERV=" + AUTORIZACIONES_CODOBSERV +
                ", AUTORIZACIONES_COPAGO=" + AUTORIZACIONES_COPAGO +
                ", AUTORIZACIONES_MODERA=" + AUTORIZACIONES_MODERA +
                ", AUTORIZACIONES_SEMANAS=" + AUTORIZACIONES_SEMANAS +
                ", AUTORIZACIONES_ESTRATO='" + AUTORIZACIONES_ESTRATO + '\'' +
                ", AUTORIZACIONES_FECHA_ANULA='" + AUTORIZACIONES_FECHA_ANULA + '\'' +
                ", AUTORIZACIONES_ANULACION='" + AUTORIZACIONES_ANULACION + '\'' +
                ", AUTORIZACIONES_IPSPRESTA='" + AUTORIZACIONES_IPSPRESTA + '\'' +
                ", AUTORIZACIONES_IPSEXPIDE='" + AUTORIZACIONES_IPSEXPIDE + '\'' +
                ", AUTORIZACIONES_HORARAD='" + AUTORIZACIONES_HORARAD + '\'' +
                ", AUTORIZACIONES_ESTANCIA='" + AUTORIZACIONES_ESTANCIA + '\'' +
                ", AUTORIZACIONES_TIPOATEN=" + AUTORIZACIONES_TIPOATEN +
                ", AUTORIZACIONES_CLASEATEN=" + AUTORIZACIONES_CLASEATEN +
                ", AUTORIZACIONES_CAUANULA=" + AUTORIZACIONES_CAUANULA +
                ", AUTORIZACIONES_COMPLEMENTO='" + AUTORIZACIONES_COMPLEMENTO + '\'' +
                ", AUTORIZACIONES_ACORCAR=" + AUTORIZACIONES_ACORCAR +
                ", AUTORIZACIONES_IMPRESA='" + AUTORIZACIONES_IMPRESA + '\'' +
                ", AUTORIZACIONES_PRO_ACOR_A=" + AUTORIZACIONES_PRO_ACOR_A +
                ", AUTORIZACIONES_SEMANAS_A=" + AUTORIZACIONES_SEMANAS_A +
                ", AUTORIZACIONES_HONO='" + AUTORIZACIONES_HONO + '\'' +
                ", AUTORIZACIONES_TIPODOC='" + AUTORIZACIONES_TIPODOC + '\'' +
                ", AUTORIZACIONES_ANEXO='" + AUTORIZACIONES_ANEXO + '\'' +
                ", AUTORIZACIONES_COBERTURA=" + AUTORIZACIONES_COBERTURA +
                ", AUTORIZACIONES_SUCURSAL='" + AUTORIZACIONES_SUCURSAL + '\'' +
                ", AUTORIZACIONES_TIPOEVO='" + AUTORIZACIONES_TIPOEVO + '\'' +
                ", AUTORIZACIONES_PROBON=" + AUTORIZACIONES_PROBON +
                ", AUTORIZACIONES_IPS='" + AUTORIZACIONES_IPS + '\'' +
                ", AUTORIZACIONES_TEVOLU=" + AUTORIZACIONES_TEVOLU +
                ", AUTORIZACIONES_TIPO_CAL=" + AUTORIZACIONES_TIPO_CAL +
                ", AUTORIZACIONES_INTERVE=" + AUTORIZACIONES_INTERVE +
                ", AUTORIZACIONES_NIVEL='" + AUTORIZACIONES_NIVEL + '\'' +
                ", AUTORIZACIONES_NUMDIAS=" + AUTORIZACIONES_NUMDIAS +
                ", AUTORIZACIONES_OBJETA=" + AUTORIZACIONES_OBJETA +
                ", AUTORIZACIONES_NBONOS=" + AUTORIZACIONES_NBONOS +
                ", AUTORIZACIONES_HORARTA='" + AUTORIZACIONES_HORARTA + '\'' +
                ", AUTORIZACIONES_PRIORIDAD='" + AUTORIZACIONES_PRIORIDAD + '\'' +
                ", AUTORIZACIONES_FECRTA='" + AUTORIZACIONES_FECRTA + '\'' +
                ", AUTORIZACIONES_FECHA_SOLICITUD='" + AUTORIZACIONES_FECHA_SOLICITUD + '\'' +
                ", AUTORIZACIONES_TEL_CONTACTO='" + AUTORIZACIONES_TEL_CONTACTO + '\'' +
                ", AUTORIZACIONES_CIU_CONTACTO='" + AUTORIZACIONES_CIU_CONTACTO + '\'' +
                ", AUTORIZACIONES_CODCAUSAL='" + AUTORIZACIONES_CODCAUSAL + '\'' +
                ", AUTORIZACIONES_RTA='" + AUTORIZACIONES_RTA + '\'' +
                ", AUTORIZACIONES_DOCUENT='" + AUTORIZACIONES_DOCUENT + '\'' +
                ", AUTORIZACIONES_ATTACH='" + AUTORIZACIONES_ATTACH + '\'' +
                ", AUTORIZACIONES_FECHA_REC_CNA=" + AUTORIZACIONES_FECHA_REC_CNA +
                ", AUTORIZACIONES_CAMBIO_PLAN='" + AUTORIZACIONES_CAMBIO_PLAN + '\'' +
                ", AUTORIZACIONES_CODIGO_REFERENCIA=" + AUTORIZACIONES_CODIGO_REFERENCIA +
                ", AUTORIZACIONES_VIGFIN='" + AUTORIZACIONES_VIGFIN + '\'' +
                ", AUTORIZACIONES_SEXO='" + AUTORIZACIONES_SEXO + '\'' +
                ", AUTORIZACIONES_DERECHO_MATERNIDAD='" + AUTORIZACIONES_DERECHO_MATERNIDAD + '\'' +
                ", AUTORIZACIONES_BEBE_GESTANTE='" + AUTORIZACIONES_BEBE_GESTANTE + '\'' +
                ", AUTORIZACIONES_ESTADO_ORDEN=" + AUTORIZACIONES_ESTADO_ORDEN +
                ", AUTORIZACIONES_PRODUCTO_CRUZADO='" + AUTORIZACIONES_PRODUCTO_CRUZADO + '\'' +
                ", AUTORIZACIONES_TIPO_AUTORIZACION='" + AUTORIZACIONES_TIPO_AUTORIZACION + '\'' +
                ", NUMERO_FUAI='" + NUMERO_FUAI + '\'' +
                ", AUTORIZACIONES_TIEMPO=" + AUTORIZACIONES_TIEMPO +
                ", AUTORIZACIONES_OBSER_CNA='" + AUTORIZACIONES_OBSER_CNA + '\'' +
                ", AUTORIZACIONES_ESPECIALES='" + AUTORIZACIONES_ESPECIALES + '\'' +
                ", AUTORIZACIONES_NUMCONSULTA=" + AUTORIZACIONES_NUMCONSULTA +
                ", AUTORIZACIONES_CORR_REMITE='" + AUTORIZACIONES_CORR_REMITE + '\'' +
                ", AUTORIZACIONES_FECHA_CIRUGIA='" + AUTORIZACIONES_FECHA_CIRUGIA + '\'' +
                ", AUTORIZACIONES_PORC_COL_PRE=" + AUTORIZACIONES_PORC_COL_PRE +
                ", AUTORIZACIONES_EN_COLA='" + AUTORIZACIONES_EN_COLA + '\'' +
                ", AUTORIZACIONES_MORA_OPTIMO='" + AUTORIZACIONES_MORA_OPTIMO + '\'' +
                ", AUTORIZACIONES_TIPO_RECOBRO=" + AUTORIZACIONES_TIPO_RECOBRO +
                ", AUTORIZACIONES_CONSECUTIVO_CTC=" + AUTORIZACIONES_CONSECUTIVO_CTC +
                ", AUTORIZACIONES_IDOFICINA_CTC='" + AUTORIZACIONES_IDOFICINA_CTC + '\'' +
                ", AUTORIZACIONES_FEC_SOLUCION='" + AUTORIZACIONES_FEC_SOLUCION + '\'' +
                ", AUTORIZACIONES_CARTA_CONSECUTIVO=" + AUTORIZACIONES_CARTA_CONSECUTIVO +
                ", AUTORIZACIONES_CARTA_ID_OFICINA='" + AUTORIZACIONES_CARTA_ID_OFICINA + '\'' +
                ", AUTORIZACIONES_INGRESO='" + AUTORIZACIONES_INGRESO + '\'' +
                ", AUTORIZACIONES_PROV_FAX='" + AUTORIZACIONES_PROV_FAX + '\'' +
                ", AUTORIZACIONES_OFI_IMPRIME='" + AUTORIZACIONES_OFI_IMPRIME + '\'' +
                ", AUTORIZACIONES_TIPO_RECAUDO='" + AUTORIZACIONES_TIPO_RECAUDO + '\'' +
                ", AUTORIZACIONES_TUTELA='" + AUTORIZACIONES_TUTELA + '\'' +
                ", AUTORIZACIONES_PROV_ESPECIALIDAD='" + AUTORIZACIONES_PROV_ESPECIALIDAD + '\'' +
                ", AUTORIZACIONES_NOM_MEDICO_INST='" + AUTORIZACIONES_NOM_MEDICO_INST + '\'' +
                ", AUTORIZACIONES_FECHA_CITA='" + AUTORIZACIONES_FECHA_CITA + '\'' +
                ", AUTORIZACIONES_HORA_CITA='" + AUTORIZACIONES_HORA_CITA + '\'' +
                ", AUTORIZACIONES_TEL_CONSULTORIO='" + AUTORIZACIONES_TEL_CONSULTORIO + '\'' +
                ", AUTORIZACIONES_CAUSA_PARCIAL='" + AUTORIZACIONES_CAUSA_PARCIAL + '\'' +
                ", USUARIO_ASIGNADO='" + USUARIO_ASIGNADO + '\'' +
                ", ESTADO_CASO='" + ESTADO_CASO + '\'' +
                ", AUTORIZACIONES_VALOR_FINAL=" + AUTORIZACIONES_VALOR_FINAL +
                ", AUTORIZACIONES_NIVEL_AUTORIZADOR='" + AUTORIZACIONES_NIVEL_AUTORIZADOR + '\'' +
                ", AUTORIZACIONES_NUMERO_REMPLAZA=" + AUTORIZACIONES_NUMERO_REMPLAZA +
                ", AUTORIZACIONES_ID_OFI_REMPLAZA='" + AUTORIZACIONES_ID_OFI_REMPLAZA + '\'' +
                ", AUTORIZACIONES_CAJA_ACORCAR=" + AUTORIZACIONES_CAJA_ACORCAR +
                ", AUTORIZACIONES_CAJA_COPAGO=" + AUTORIZACIONES_CAJA_COPAGO +
                ", AUTORIZACIONES_CAJA_MODERA=" + AUTORIZACIONES_CAJA_MODERA +
                ", AUTORIZACIONES_CAJA_FECHA='" + AUTORIZACIONES_CAJA_FECHA + '\'' +
                ", AUTORIZACIONES_OFICINA_CAJA=" + AUTORIZACIONES_OFICINA_CAJA +
                ", AUTORIZACIONES_DIF_REMPLAZA=" + AUTORIZACIONES_DIF_REMPLAZA +
                ", AUTORIZACIONES_TIPO_IPS='" + AUTORIZACIONES_TIPO_IPS + '\'' +
                ", AUTORIZACIONES_IPS_HOSP='" + AUTORIZACIONES_IPS_HOSP + '\'' +
                ", AUTORIZACIONES_NROCASOATEP=" + AUTORIZACIONES_NROCASOATEP +
                ", AUTORIZACIONES_OFIATEP='" + AUTORIZACIONES_OFIATEP + '\'' +
                ", AUTORIZACIONES_ESTADO_ATEP=" + AUTORIZACIONES_ESTADO_ATEP +
                ", AUTORIZACIONES_AGE_NROCITA=" + AUTORIZACIONES_AGE_NROCITA +
                ", AUTORIZACIONES_IPS_INTEGRADA='" + AUTORIZACIONES_IPS_INTEGRADA + '\'' +
                ", AUTORIZACIONES_TIPO_REMIPS='" + AUTORIZACIONES_TIPO_REMIPS + '\'' +
                ", AUTORIZACIONES_TIPIDE_REMIPS='" + AUTORIZACIONES_TIPIDE_REMIPS + '\'' +
                ", AUTORIZACIONES_NUMIDE_REMIPS='" + AUTORIZACIONES_NUMIDE_REMIPS + '\'' +
                ", AUTORIZACIONES_TIPO_REMITENTE='" + AUTORIZACIONES_TIPO_REMITENTE + '\'' +
                ", AUTORIZACIONES_DIAS_IMPRESION=" + AUTORIZACIONES_DIAS_IMPRESION +
                ", AUTORIZACIONES_NROCITA_IPS=" + AUTORIZACIONES_NROCITA_IPS +
                ", AUTORIZACIONES_PAQUETE_PYP='" + AUTORIZACIONES_PAQUETE_PYP + '\'' +
                ", AUTORIZACIONES_FECHA_INGRESO=" + AUTORIZACIONES_FECHA_INGRESO +
                ", AUTORIZACIONES_FECHA_EGRESO=" + AUTORIZACIONES_FECHA_EGRESO +
                ", AUTORIZACIONES_NUEVO_POS='" + AUTORIZACIONES_NUEVO_POS + '\'' +
                ", AUTORIZACIONES_MESES_PRE=" + AUTORIZACIONES_MESES_PRE +
                ", AUTORIZACIONES_NUMORDEN=" + AUTORIZACIONES_NUMORDEN +
                ", AUTORIZACIONES_TIPO_ORDEN=" + AUTORIZACIONES_TIPO_ORDEN +
                ", AUTORIZACIONES_POSPURO='" + AUTORIZACIONES_POSPURO + '\'' +
                ", AUTORIZACIONES_PREPAGO_VIGENTE='" + AUTORIZACIONES_PREPAGO_VIGENTE + '\'' +
                ", AUTORIZACIONES_NROSOLICITUD=" + AUTORIZACIONES_NROSOLICITUD +
                ", AUTORIZACIONES_NRO_MINSAL=" + AUTORIZACIONES_NRO_MINSAL +
                ", VALOR_TECNICA=" + VALOR_TECNICA +
                ", VALOR_PROVISION=" + VALOR_PROVISION +
                ", VALORIZA='" + VALORIZA + '\'' +
                ", CIERRE_EVENTO=" + CIERRE_EVENTO +
                ", ID_ORIGEN_CANAL=" + ID_ORIGEN_CANAL +
                ", CodMensajeSalud='" + CodMensajeSalud + '\'' +
                ", AUTORIZACIONES_FECHAORDENMEDICA=" + AUTORIZACIONES_FECHAORDENMEDICA +
                ", VALOR_DESCUENTOS=" + VALOR_DESCUENTOS +
                ", VALOR_NETO=" + VALOR_NETO +
                ", PORCENTAJE_RECOBRO=" + PORCENTAJE_RECOBRO +
                ", FECHA_VALORIZACION='" + FECHA_VALORIZACION + '\'' +
                '}';
    }
}

